name: Eric Mazzone
favicon: null
layout_spectrum: 0.43960616178810596
typography_spectrum: 0.02047548908740282
title: Eric Mazzone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.02537292684428394
  lightness: 0.4109557932242751
  saturation: 0.2910629992838949
  rhythmicContrast: 0.6795754733029753
purpose: []
